#Your workflow name.
name: Deploy to heroku.

# Run workflows on every push to main branch.

on:
  push:
    branches: [main]
    
# Your Workflows jobs.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Check-out your repository.
    -name: Checkout
     uses: actions/checkout@v2


### IMPORTANT PART ###

    -name: Build, Push and Release a Docker container to Heroku. # Your custom step name
     uses: gonuit/heroku-docker-deploy@v1.3.3 # Github  action name (leave it as it is)

     with: 
      # Below you must provide variables for your Heroku app.
      # The email address associated with your Heroku app.
      # email: my.email@example.com
      email: ${{secrets.HEROKU_EMAIL}}

      # Heroku API key associated with provided user's email.
      # API Key is available  under your  Heroku account settings.
      heroku_api_key: ${{ secrets.HEROKU_API_KEY }}

      # (Optional, default: "./")
      # Dockerfile directory.
      # For example, if you have a Dockerfile in the root your project, leave it as follows;
      dockerfile_directory: ./

      #(Optinal, default: "Dockerfile")
      # Dockerfile name.
      dockerfile_name: Dockerfile

      #(Optional, default: "")
      # Additional optinal of docker build command.
      docker_options: "--no-cache"

      # (Optionl, default: "web")
      # select the process type for which you want docker container to be uploaded
      # By default, this argument is set to "web"
      # For more information look at https:// devcenter.heroku.com/articles/process-model
      process_type: web